spring:
  application:
    name: cloud-consumer-user
    
server:
  port: 9000
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true #注册中心保存我的ip
