spring: 
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.32.128:3306/atcrowdfunding?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: SCW-USER
  redis:
    host: 192.168.32.128
#    type: com.alibaba.druid.pool.DruidDataSource
#    filters: stat
 
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
 
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance: 
    prefer-ip-address: true
 
server:
  port: 7000
  
swagger2: 
  enable: true
  

